create table if not exists tbl_domain (
       f_idx integer generated by default as identity,
       f_name varchar(255) unique not null,
       f_status integer default 0,
       primary key (f_idx)
);


create table if not exists tbl_mailbox (
       f_idx integer generated by default as identity,
       f_aidx integer not null,
       f_name varchar(255) not null,
       primary key (f_idx)
);


create table if not exists tbl_maillist (
       f_idx integer generated by default as identity,
       f_midx integer not null,
       f_uid varchar(64) not null,
       f_emlpath varchar(255) not null,
       f_envfrom varchar(255),
       f_envto varchar(4096),
       mail_attribute CLOB not null,
       primary key (f_idx)
);


create table if not exists tbl_relay (
       f_idx integer generated by default as identity,
       f_ip varchar(255) not null,
       f_type integer not null default 0 comment '0 : ip, 1 : subnet',
       f_didx integer not null,
       primary key (f_idx)
);


create table if not exists tbl_user (
       f_idx integer generated by default as identity,
       f_pwd varchar(255) not null,
       f_id varchar(255) not null,
       f_didx integer not null,
       primary key (f_idx)
);

alter table tbl_mailbox add constraint UKagitn7q032w700b5qacg3dp33 unique (f_aidx, f_name);
alter table tbl_user add constraint UK3fu3bjt4oqoas9mw7a9hgjqj unique (f_didx, f_id);
alter table tbl_maillist add constraint FKrum0bpllrirylcbalft9p8b33 foreign key (f_midx) references tbl_mailbox;
alter table tbl_relay add constraint FKntcxxou6j8cmrlv5qvr0dk04d foreign key (f_didx) references tbl_domain;
alter table tbl_user add constraint FK3rjpun8jutuk6nent1m507wjc foreign key (f_didx) references tbl_domain;

create index if not exists idx_mailbox on tbl_mailbox (f_aidx);
create index if not exists idx_domain on tbl_domain (f_name);
create index if not exists idx_maillist on tbl_maillist (f_midx);
create index if not exists idx_relay on tbl_relay (f_didx);


INSERT INTO tbl_domain(f_idx, f_name, f_status) VALUES(1, 'test.com', 0);
INSERT INTO tbl_user(f_idx, f_id, f_didx, f_pwd) VALUES(1, 'test', 1, '0ffe1abd1a08215353c233d6e009613e95eec4253832a761af28ff37ac5a150c');
INSERT INTO tbl_mailbox(f_aidx, f_name) VALUES(1, 'inbox');
INSERT INTO tbl_mailbox(f_aidx, f_name) VALUES(1, 'sent');
INSERT INTO tbl_mailbox(f_aidx, f_name) VALUES(1, 'spam');